config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :courses
  get "up" => "rails/health#show", as: :rails_health_check

  #2
  #get 'welcome/index'
  root 'welcome#index'

  resources :students


=begin
  namespace :admin do
    resources :students
  end
=end
  scope module: :admin do
    resources :students
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

  belongs_to :student
end

app/models/course.rb
class Course < ApplicationRecord

  #many_to_many avec student
  has_and_belongs_to_many :students

end

app/models/demo.rb
class Demo < ApplicationRecord

  #one sub_module
  has_one :sub_demo
end

app/models/departement.rb
class Departement < ApplicationRecord
  has_one :manager
  has_one :manager_history, through: :manager
end

app/models/manager.rb
class Manager < ApplicationRecord
  belongs_to :departement
  has_one :manager_history
end

app/models/manager_history.rb
class ManagerHistory < ApplicationRecord
  belongs_to :manager
end

app/models/project.rb
class Project < ApplicationRecord

  has_many  :student_projects
  has_many  :students, through: :student_projects
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :blogs
  #validation in models/concerns
  included Validatable


  validates :email, uniqueness: true
  validates :name, :lastname, length: { minimum: 3, maximum: 50 }
  validates :name, :lastname, format: { with: /\A[a-z,A-Z]+\z/,message: 'Only lettre are allowed' }
  validates :age, presence: true ,numericality: { only_integer: true }

  validate :validate_student_age
  def validate_student_age
    if self.date_of_birth.present?
      age = Date.today.year - self.date_of_birth.year
      if age<15
        errors.add(:date_of_birth, "Must be greater than 15 years old.")
      end
    end
  end


  def full_name
    "#{name} #{lastname}"
  end

  def age
    if date_of_birth.present?
      Date.today.year - date_of_birth.year
    else
      nil
    end
  end

  # before_create :display_greetings
  # def display_greetings
  #puts 'Hello , you executed before action  callback'
  # end

  #many_to_many avec courses
  has_and_belongs_to_many :courses
  #has_and_belongs_to_many :courses ,join_table: "students_courses"

  #has_many  avec project
  has_many :student_projects
  has_many :projects, through: :student_projects
end

app/models/student_project.rb
class StudentProject < ApplicationRecord
  belongs_to :student
  belongs_to :project
end

app/models/sub_demo.rb
class SubDemo < ApplicationRecord
  belongs_to :demo
end

app/controllers/admin/students_controller.rb
class StudentsController < ApplicationController <ApplicationController

  # TODO -Implement CRUD Operation
end

app/controllers/students_controller.rb
# app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :set_student, only: %i[show edit update destroy]
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path , notice:  'Student Created'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @student.update(student_params)
      redirect_to student_path(@student), notice:  'Student Updated'
    else
      render :edit
    end
  end

  def destroy
  @student.destroy
    redirect_to students_path, notice:  'Student Deleted'
  end

  private

  def student_params
    params.require(:student).permit(:name, :lastname, :email, :date_of_birth, :contact, :address)
  end

  def  set_student
    @student = Student.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assemblies_helper.rb
module AssembliesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/students/_form.html.erb
<%= form_with model: student do |form| %>

  <% if @student.errors.any?  %>
    <% @student.errors.full_messages.each do |message| %>
      <p> <%= message %> </p>
    <% end %>
  <% end %>

  <%= form.label :name %>
  <%= form.text_field :name %> <br>



  <%= form.label :lastname %>
  <%= form.text_field :lastname %> <br>



  <%= form.label :email %>
  <%= form.email_field :email %> <br>

  <%= form.label :date_of_birth %>
  <%= form.date_field :date_of_birth %> <br>

  <%= form.label :adress %>
  <%= form.text_field :adress %> <br>

  <%= form.label :contact %>
  <%= form.text_field :contact %> <br>
  <br>
  <%= form.submit %>
<% end %>

app/views/students/edit.html.erb
<h1>Edit Student</h1>


<%= render "form", student: @student %>

app/views/students/index.html.erb
 <%= notice %>
<h1>Listing student</h1>

<%= link_to 'New Student', new_student_path %>
<table>
  <thead>
    <tr>
      <th>fisrt name</th>
      <th>lastname</th>
      <th>email</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
  <% @students.each do |student| %>
  <tr>
    <td><%= student.name %></td>
    <td><%= student.lastname %></td>
    <td><%= student.email %></td>
   <td><%= link_to 'View', student %></td>
    <td><%= link_to 'Edit', edit_student_path(student) %></td>
    <td><%= link_to 'Delete', student_path(student), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>



  </tr>
  <% end %>
  </tbody>
</table>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render "form", student: @student %>

app/views/students/show.html.erb
<h1>Detail Student</h1>

<!--<p><strong>Name:</strong> <%#=@student.name %></p>-->
<!--<p><strong>Lastname:</strong> <%#=@student.lastname %></p>-->
<!--<p><strong> Name : </strong>  <%#= @student.name %> <%#= @student.lastname %></p>-->

<p><strong> Name : </strong>  <%#= @student.full_name%></p>
<p><strong>Email :</strong> <%=@student.email %></p>
<p><strong>Age :</strong> <%=@student.age %></p>

<%= link_to 'Back', students_path %> |     <%= link_to 'Edit', edit_student_path(@student) %>